initial commit
yiocardamone/python-weather-api pull request #1
Opened 2023-12-29 21:45 UTC by yiocardamone

2023-12-30 14:20 UTC, syols reviewed
Ревью кода, остальную логику (там много вопросов) лучше посмотреть после текущих правок

2023-12-30 14:20 UTC, syols commented on authorithy.py
> +        print('Login Error!')
В конце файла с исходным кодом необходимо добавлять пустую строку. Тут и далее

2023-12-30 14:20 UTC, syols commented on main.py
> +@app.route("/weather")  # здесь один эндпоинт он один общий можно добавлять, но они не меняются
Лучше  ручки вынести в отдельный фаил

2023-12-30 14:20 UTC, syols commented on main.py
> +api_key = "f5b39ac7a82e4dbd8a5120339231312"  # Paste Your API ID Here
Приватная информация, в идеале, должна быть спрятана
Лучше перенести это в конфиг, а в самом конфиге залей "Paste Your API ID Here".

2023-12-30 14:20 UTC, syols commented on main.py
> +final_URL = "http://api.weatherapi.com/v1/current.json?key=" + api_key + "&q={}&aqi={}"
Эта информация не должна быть тут.

2023-12-30 14:20 UTC, syols commented on main.py
> +final_URL = "http://api.weatherapi.com/v1/current.json?key=" + api_key + "&q={}&aqi={}"
Почитай про формат строк через f""

2023-12-30 14:20 UTC, syols commented on main.py
> +    return str(result.temperature) + " " + str(result.lat) + " " + str(result.lon)
Поправь формат строк

2023-12-30 14:20 UTC, syols commented on model/geo_temperature.py
> +from dataclasses import dataclass
Лучше переименовать в models

2023-12-30 14:20 UTC, syols commented on model/geo_temperature.py
> +    temperature: float
Значения по умолчанию?

2023-12-30 14:20 UTC, syols commented on model/simplified_inheritance.py
> +    API_KEY = "f5b39ac7a82e4dbd8a5120339231312"  # Paste Your API ID Here
Дубли в коде

2023-12-30 14:20 UTC, syols commented on model/simplified_inheritance.py
> +    FINAL_URL = "http://api.weatherapi.com/v1/current.json?key=" + API_KEY + "&q={}&aqi={}"
Это приватная информация?

2023-12-30 14:20 UTC, syols commented on model/simplified_inheritance.py
> +        data = result.json()
Тут может быть исключение, надо обработать

2023-12-30 14:20 UTC, syols commented on model/simplified_inheritance.py
> +    FINAL_URL = "http://api.weatherapi.com/v1/current.json?key=" + API_KEY + "&q={}&aqi={}"
URL так не строят

2023-12-30 14:20 UTC, syols commented on model/simplified_inheritance.py
> +    FINAL_URL = "http://api.weatherapi.com/v1/current.json?key=" + API_KEY + "&q={}&aqi={}"
Посмотри: `urllib.parse.urlparse`

2023-12-30 14:20 UTC, syols commented on model/simplified_inheritance.py
> +        temperature = data['current']['temp_c']
А что будет, если с сервера этот ключ не придет? см `get`

2023-12-30 14:20 UTC, syols commented on model/simplified_inheritance.py
> +        return str(temperature) + " " + str(coordinate_lat) + " " + str(coordinate_lon)
Форматирование

2023-12-30 14:20 UTC, syols commented on model/simplified_inheritance.py
> +if __name__ == '__main__':
Зачем это тут?

2023-12-30 14:20 UTC, syols commented on model/test_class_model.py
> +from abc import ABC
Перенеси это в папку tests

2023-12-30 14:20 UTC, syols commented on model/test_class_model.py
> +from abc import ABC
А где сами тесты?

2023-12-30 14:20 UTC, syols commented on model/test_class_model.py
> +class TestClassModel(IWeatherRequester, ABC):
ClassModel?
Мб OpenWeatherRequesterMock?

2023-12-30 14:20 UTC, syols commented on model/weather_requester.py
> +        pass
замени на `raise NotImplementedError`

2023-12-30 14:20 UTC, syols commented on model/weather_requester.py
> +    def request_conversion(self):
Добавь тут и во всем проекте [type hints](https://docs.python.org/3/library/typing.html)

2023-12-30 14:20 UTC, syols commented on model/weather_requester.py
> +        pass
Почитай про утилиты isort, mypy и black. Проверь свой код

2023-12-30 14:20 UTC, syols commented on main.py
> +from model.test_class_model import *
не импортируй со *

2023-12-30 14:20 UTC, syols commented on authorithy.py
> +import time
Для чего этот фаил?

2023-12-30 14:20 UTC, syols commented on main.py
> +from flask import Flask
Тут используются зависимости, почитай про pip install и [managing-dependencies](https://www.jetbrains.com/help/pycharm/managing-dependencies.html)

В идеале попробовать поработать с poetry

2023-12-30 14:20 UTC, syols commented on model/test_class_model.py
> +        tom = GeoTemperature(self.temperature, self.lat, self.lon)
мб назвать иначе? tom?

2023-12-30 14:20 UTC, syols commented on model/simplified_inheritance.py
> +        self.city = city
Все переменные публичные?

2023-12-30 14:20 UTC, syols commented on main.py
> +def index():
А зачем эта ручка?

2023-12-30 14:20 UTC, syols commented on model/test_class_model.py
> +        return tom
можно же сразу вернуть `GeoTemperature`

2023-12-30 14:20 UTC, syols commented on main.py
> +    return str(result.temperature) + " " + str(result.lat) + " " + str(result.lon)
Тут лучше вернуть json

2023-12-30 14:20 UTC, syols commented on main.py
> +@app.route("/weather")  # здесь один эндпоинт он один общий можно добавлять, но они не меняются
Забыли HTTP метод

2024-01-07 11:57 UTC, syols commented on .gitignore
> +config.py
Конфиг лучше в json/yaml и хорошо бы его залить, просто без ключей

2024-01-07 11:58 UTC, syols commented on endpoints.py
> +app = Flask(__name__)
А зачем тут держать app?

2024-01-07 11:58 UTC, syols commented on model/simplified_inheritance.py
> +class SimplifiedInheritance(IWeatherRequester, ABC):  # instance этих прослоек хранятся в сервере, это к вопросу о
ABC тут точно нужно?

2024-01-08 20:46 UTC, yiocardamone commented on authorithy.py
> +        print('Login Error!')
+

2024-01-08 20:46 UTC, yiocardamone commented on main.py
> +@app.route("/weather")  # здесь один эндпоинт он один общий можно добавлять, но они не меняются
+

2024-01-08 20:46 UTC, yiocardamone commented on main.py
> +api_key = "f5b39ac7a82e4dbd8a5120339231312"  # Paste Your API ID Here
+

2024-01-08 20:46 UTC, yiocardamone commented on main.py
> +final_URL = "http://api.weatherapi.com/v1/current.json?key=" + api_key + "&q={}&aqi={}"
+

2024-01-08 20:46 UTC, yiocardamone commented on main.py
> +final_URL = "http://api.weatherapi.com/v1/current.json?key=" + api_key + "&q={}&aqi={}"
+

2024-01-08 20:46 UTC, yiocardamone commented on model/simplified_inheritance.py
> +        self.city = city
+

2024-01-08 20:46 UTC, yiocardamone commented on main.py
> +def index():
+

2024-01-08 20:47 UTC, yiocardamone commented on model/test_class_model.py
> +        return tom
+

2024-01-08 20:47 UTC, yiocardamone commented on main.py
> +    return str(result.temperature) + " " + str(result.lat) + " " + str(result.lon)
+

2024-01-08 20:47 UTC, yiocardamone commented on main.py
> +@app.route("/weather")  # здесь один эндпоинт он один общий можно добавлять, но они не меняются
+

2024-01-08 20:47 UTC, yiocardamone commented on .gitignore
> +config.py
+

2024-01-08 20:47 UTC, yiocardamone commented on endpoints.py
> +app = Flask(__name__)
+

2024-01-08 20:47 UTC, yiocardamone commented on model/simplified_inheritance.py
> +class SimplifiedInheritance(IWeatherRequester, ABC):  # instance этих прослоек хранятся в сервере, это к вопросу о
+

2024-01-08 20:47 UTC, yiocardamone commented on main.py
> +    return str(result.temperature) + " " + str(result.lat) + " " + str(result.lon)
+

2024-01-08 20:48 UTC, yiocardamone commented on model/geo_temperature.py
> +from dataclasses import dataclass
+

2024-01-08 20:48 UTC, yiocardamone commented on model/geo_temperature.py
> +    temperature: float
+

2024-01-08 20:48 UTC, yiocardamone commented on model/simplified_inheritance.py
> +    API_KEY = "f5b39ac7a82e4dbd8a5120339231312"  # Paste Your API ID Here
+

2024-01-08 20:48 UTC, yiocardamone commented on model/simplified_inheritance.py
> +    FINAL_URL = "http://api.weatherapi.com/v1/current.json?key=" + API_KEY + "&q={}&aqi={}"
+

2024-01-08 20:48 UTC, yiocardamone commented on model/simplified_inheritance.py
> +        data = result.json()
+

2024-01-08 20:48 UTC, yiocardamone commented on model/simplified_inheritance.py
> +    FINAL_URL = "http://api.weatherapi.com/v1/current.json?key=" + API_KEY + "&q={}&aqi={}"
+

2024-01-08 20:48 UTC, yiocardamone commented on model/simplified_inheritance.py
> +        temperature = data['current']['temp_c']
-

2024-01-08 20:48 UTC, yiocardamone commented on model/simplified_inheritance.py
> +        return str(temperature) + " " + str(coordinate_lat) + " " + str(coordinate_lon)
+

2024-01-08 20:48 UTC, yiocardamone commented on model/simplified_inheritance.py
> +if __name__ == '__main__':
+

2024-01-08 20:48 UTC, yiocardamone commented on model/test_class_model.py
> +from abc import ABC
+

2024-01-08 20:48 UTC, yiocardamone commented on model/test_class_model.py
> +class TestClassModel(IWeatherRequester, ABC):
+

2024-01-08 20:49 UTC, yiocardamone commented on model/weather_requester.py
> +        pass
+

2024-01-08 20:49 UTC, yiocardamone commented on model/weather_requester.py
> +    def request_conversion(self):
+

2024-01-08 20:49 UTC, yiocardamone commented on model/weather_requester.py
> +        pass
+

2024-01-08 20:49 UTC, yiocardamone commented on main.py
> +from model.test_class_model import *
+

2024-01-08 20:49 UTC, yiocardamone commented on model/test_class_model.py
> +        tom = GeoTemperature(self.temperature, self.lat, self.lon)
+

2024-01-10 21:30 UTC, syols commented on config.json
Добавь сам json плиз

2024-01-10 21:35 UTC, syols commented on main.py
> +@app.route("/weather")  # здесь один эндпоинт он один общий можно добавлять, но они не меняются
Ничего не изменилось?

2024-01-10 21:41 UTC, syols commented on authorithy.py
> +    "user[password]": "18283848Qw",  # Пароль
Вау

2024-01-10 21:43 UTC, syols commented on authorithy.py
> +    "user[password]": "18283848Qw",  # Пароль
Да, рабочий. Интересно, а где еще эта связка email/password используется?

2024-01-10 21:44 UTC, syols commented on authorithy.py
> +time.sleep(2)  # Пауза 2 сек :)
Это очень плохо. Даже если в тестах есть таймауты, значит что-то не так

2024-01-10 21:45 UTC, syols commented on authorithy.py
> +if __name__ == "__main__":
А зачем тут __main__?

2024-01-10 21:46 UTC, syols commented on main.py
> +app.add_url_rule("/weather", "get_weather", get_weather, methods=["GET"])
Ручку так и не вынесли

2024-01-10 21:47 UTC, syols commented on model/weather_requester.py
> +    def request_conversion(self):
Нет, это не исправлено. Не хватает возвращаемых значений. 
Проверь тайпинг через mypy

2024-01-10 22:02 UTC, syols requested changes

2024-01-10 22:02 UTC, syols commented on tests/open_weather_requester_mock.py
> +class OpenWeatherRequesterMock(IWeatherRequester, ABC):
А где сами тесты?

2024-01-10 22:02 UTC, syols commented on model/simplified_inheritance.py
> +    def find_values(obj: dict):
Круто, что ты попробовал сделать свой десереализатор, но лучше взять pydantic/marshmallow.

2024-01-10 22:02 UTC, syols commented on model/simplified_inheritance.py
> +    def find_values(obj: dict):
сама логика проверки через isinstance спорная + рекурсия. Но хорошо, что попробовал

2024-01-10 22:02 UTC, syols commented on model/simplified_inheritance.py
> +    path = os.path.join(current_directory, "config.json")
1. Разделение ролей: конфиг лучше передавать в параметрах и инициализировать единожды
2. Десереализацию конфига лучше сделать через pydantic/marshmallow и т.д

2024-01-10 22:02 UTC, syols commented on model/simplified_inheritance.py
> +                    result.raise_for_status()  # Проверяем наличие ошибки в ответе.
Круто

2024-01-10 22:02 UTC, syols commented on model/simplified_inheritance.py
> +                        print(f"URL-адрес запроса API недействителен: {err}")
Нет, лучше создать набор ошибок и raise'ить их тут.
В самом обработчике ручки /weather/ вылавливать ошибку и возвращать уже наш HTTP-код ошибки в ответе

2024-01-10 22:02 UTC, syols commented on model/simplified_inheritance.py
> +                support_params = subjects["support_params"]
Опять же - десереализация

2024-01-10 22:05 UTC, syols commented on model/weather_requester.py
> +        pass
Это не исправлено (mypy, black)

2024-01-10 22:08 UTC, syols commented on routes.py
> +    return json.dumps(result.__dict__)
смотри flask.jsonify

2024-01-10 22:10 UTC, syols commented on model/simplified_inheritance.py
> +                    result.raise_for_status()  # Проверяем наличие ошибки в ответе.
но, эта конструкция должна быть где-то обработана, тк летит исключение (например в get_weather в routes.py)

2024-01-10 22:10 UTC, syols commented on tests/open_weather_requester_mock.py
> +class OpenWeatherRequesterMock(IWeatherRequester, ABC):
ABC?

2024-01-10 22:11 UTC, syols commented on tests/open_weather_requester_mock.py
> +        self.city = city
публичные параметры, уже вроде правили

2024-01-10 22:11 UTC, syols commented on model/simplified_inheritance.py
> +        self.coordinate = coordinate
Публичные параметры

2024-01-10 22:12 UTC, syols commented on authorithy.py
> +        print("Login OK!")
Предлагаю убрать принты, для этих целей используй логгирование (https://flask.palletsprojects.com/en/1.1.x/logging/)

2024-01-10 22:15 UTC, syols commented on model/simplified_inheritance.py
> +                    if isinstance(v, list):
Посмотри что такое тернарный условный оператор

2024-01-10 22:16 UTC, syols commented on model/simplified_inheritance.py
> +    current_directory = os.getcwd()
Плохая практика, почитай про абсолютные/относительные пути

2024-01-10 22:17 UTC, syols commented on model/simplified_inheritance.py
> +                        print(f"URL-адрес запроса API недействителен: {err}")
далее тоже самое

2024-01-10 22:18 UTC, syols commented on model/simplified_inheritance.py
> +                lat = support_params[location][0]  # the name of the "location" field
так делать плохо, у тебя там должен быть tuple. Lat/lon пара значений, можно так:
`lat, lon = support_params[location]`

2024-01-19 19:42 UTC, syols commented on config.json
> +        "apikey": "Sb5mxppt7iHIRRTMwXmV3SzVrNXT9AO9"
Убери ключи плз

2024-01-19 19:47 UTC, syols commented on main.py
> +app.add_url_rule("/weather", "get_weather", get_weather, methods=["GET"])
routes.get_weather - поменять в views.get_weather
app.add_url_rule("/weather", "get_weather", get_weather, methods=["GET"]) - в routes

2024-01-19 19:48 UTC, syols commented on model/simplified_inheritance.py
> +        return next((v[0] for k, v in obj.items() if k == key and isinstance(v, list)), None) if isinstance(obj, dict) \
Нет десериализации, см комменты

2024-01-19 19:50 UTC, syols commented on authorithy.py
> +        print("Login OK!")
app.logger и тд

2024-01-19 19:53 UTC, syols commented on model/simplified_inheritance.py
> +    path = "./config.json"
Публичный снова параметр

2024-01-19 19:55 UTC, syols commented on main.py
> +from flask import Flask
pip freeze

2024-01-19 20:04 UTC, syols commented on model/simplified_inheritance.py
> +        with open(self.path) as f:
Каждый раз грузишь конфиг?

2024-01-21 09:18 UTC, syols commented on model/serialize_tomorrow.py
> +        self.cloudBase = cloudBase
Дубли со Shcema, хорошо бы поправить

2024-01-25 20:02 UTC, syols commented on model/simplified_inheritance.py
> +        for line in self.config.items():
можно сделать: for k, v in self.config.items():

В любом случае, конфиг надо десереализовать в класс и не забирать данные из дикта

2024-01-25 20:20 UTC, syols commented on model/simplified_inheritance.py
> +        for line in self.config.items():
`def __init__(self, coordinate: str, config: dict): ` выше config определен как dict

2024-01-25 20:20 UTC, syols commented on model/simplified_inheritance.py
> +        for line in self.config.items():
for line in self.config.items():
url = line[1]["url"]
key = line[1]["key"]

тоже dict

2024-01-25 20:28 UTC, syols commented on model/simplified_inheritance.py
> +        for line in self.config.items():
см TypedDict

2024-02-03 22:40 UTC, syols commented on model/status_code.py
> +    RESPONSE_CODE_BAD_REQUEST = 400
https://docs.python.org/3/library/http.html можно не изобретать

2024-02-03 22:41 UTC, syols commented on serialize_config.py
> +"""schema.py"""
это для примера было - можно удалить

2024-02-03 22:43 UTC, syols commented on views.py
> +            raise
Неправильно рэйзить ошибку тут, надо либо ее тут перехватывать и только писать в лог - log.error либо возвращать статус код в ручке (отличный от 500)

2024-02-03 22:44 UTC, syols commented on views.py
> -    result = SimplifiedInheritance("55.75, 37.62", g.config).request_conversion()
Хардкод нужно убрать - в ручке должны быть эти query-параметры

2024-02-03 22:44 UTC, syols commented on model/simplified_inheritance.py
> +            raise CustomException("The API request URL is invalid",
CustomException - не оч удачное название

2024-02-03 22:49 UTC, syols commented on exceptions/weather_exception.py
> +        self.message = message
Публичные параметры, ну сколько их уже? Ответь на этот вопрос, если читаешь ревью!

2024-02-05 20:19 UTC, syols commented on views.py
> +    result = SimplifiedInheritance("55.75, 37.62", g.result).request_conversion()
Хардкод

2024-02-05 20:19 UTC, syols commented on views.py
> +    result = SimplifiedInheritance("55.75, 37.62", g.result).request_conversion()
Обработка ошибок тут

2024-02-05 20:23 UTC, syols commented on model/simplified_inheritance.py
> +class SimplifiedInheritance(IWeatherRequester):
WeatherApiRequester

2024-02-05 20:43 UTC, syols commented on serialize_config.py
> +import dataclasses
переименовать в config.py

2024-02-05 20:46 UTC, syols commented on config.json
> +  "arr": [
?

2024-02-05 20:49 UTC, syols commented on views.py
> +    with open(_path, 'r') as f:
перенести в config.py

2024-02-05 20:50 UTC, syols commented on views.py
> +def before_request():
тут только создание инстанса класса Config и передача в ручку

2024-02-05 20:50 UTC, syols commented on serialize_config.py
> +@dataclasses.dataclass
Тут что-то не то

2024-02-05 20:54 UTC, syols commented on config.json
> +  "arr": [
Структура:
{
   "api.weatherapi.com":
        {"key": "__INSERT_KEY_HERE__"}
   "api.tomorrow.io":
        {"key": "__INSERT_KEY_HERE__"}
}

2024-02-05 20:56 UTC, syols commented on model/simplified_inheritance.py
> +class SimplifiedInheritance(IWeatherRequester):
IWeatherRequester
    WeatherAPIRequester
    TomorrowIORequester

2024-02-05 20:59 UTC, syols commented on model/weather_requester.py
> +class IWeatherRequester(ABC):
IWeatherRequesterBase

2024-03-04 21:11 UTC, syols commented on errors/external_service_base_exception.py
> +class ExternalServiceClientException(ExternalServiceBaseException):
сlass ExternalServiceClientException(BaseException):
    pass

2024-03-04 21:12 UTC, syols commented on errors/external_service_base_exception.py
> +class ExternalServiceClientException(ExternalServiceBaseException):
зачем дубли

2024-04-08 23:00 UTC, merged